### ISSUE TITLE
Zooqle periodic crash

### ISSUE THREAD

**Issue by skwerlman** [sergiotapia/magnetissimo#102]
```
[info] Starting Zooqle crawler
[error] GenServer Magnetissimo.Crawler.Zooqle terminating
** (ArgumentError) argument error
    (stdlib) queue.erl:157: :queue.out(:ok)
    (magnetissimo) lib/magnetissimo/crawler/zooqle.ex:45: Magnetissimo.Crawler.Zooqle.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :work
State: :ok
[info] [Zooqle] Finding torrents in listing page: https://zooqle.com/browse/movies/?s=dt&v=t&sd=d
```

I'm not sure of the reason, but I'll dig into it later once I've fixed #100

**Comment by tchoutri** [comment]
Yeah I saw that a few days ago, I'm super surprised that it happens! I guess we should use Dialyzer much more in the future…
Meanwhile, do you think it's possible to track down every call to `:queue.out`? This simple `:ok` makes me wonder if we've got a `Logger` call at the end of a function that hijacks its type…

**Comment by skwerlman** [comment]
It turns out Zooqle supports OpenSearch, which returns results as an RSS feed. I have a feeling that rewriting this will get rid of the bug if its anywhere in the crawler itself.
