### ISSUE TITLE
Slack chatroom

### ISSUE THREAD

**Issue by tchoutri** [sergiotapia/magnetissimo#106]
@pahakalle 
@skwerlman 
@sergiotapia 

I opened a Slack chatroom so we can have better coordination about Magnetissimo's development.
All the details are in the README. I feel this could prevent some headache in the future :P

**Comment by sergiotapia** [comment]
I created a new Slack workspace. What's your email @pahakalle @skwerlman @tchoutri - I'll send you guys invites.

**Comment by tchoutri** [comment]
@sergiotapia but isn't that too overkill?
my slack email address is "theophile + slack @ choutri . eu"

**Comment by skwerlman** [comment]
skw at tetrarch dot co

**Comment by pahakalle** [comment]
pahakalle (at) protonmail (dot) ch

**Comment by sergiotapia** [comment]
Invites sent!

@tchoutri I like the idea of a Magnetissimo slack group. Nice place to discuss features
