### ISSUE TITLE
Systemd service

### ISSUE THREAD

**Issue by Bechrissed** [sergiotapia/magnetissimo#115]
Anybody has a working systemd service configuration for Magnetissimo?

I'm trying to set one up but i'm unable to get it working....

**Comment by tchoutri** [comment]
@Bechrissed I deploy on FreeBSD so I don't have to worry about systemd, but @apexo published a Systemd Unit in this comment: https://github.com/sergiotapia/magnetissimo/issues/59#issuecomment-276895934

**Comment by skwerlman** [comment]
its worth noting that that unit file will need to be edited to use `phx.server` instead of `phoenix.server`

**Comment by Bechrissed** [comment]
Thanks! Will have a look!
