### ISSUE TITLE
Can we detect what's in a torrent?

### ISSUE THREAD

**Issue by agustif** [sergiotapia/magnetissimo#12]
I'm thinking on having some kind of ways to categorize or tag torrents, either by machine learning or by user_input

I'd be neat once one has a subset of torrents to movies, to be able to match them by title to an API like TMDb. 
like k*t did with movie_posters, ratings, imdb links and such

**Comment by sergiotapia** [comment]
Doing something like that would be interesting. I don't have any machine learning experience.

The TMDb api seems easy enough to use, but again we would need to detect what torrents belongs to a movie or tv show and 'group' them into the right 'asset'. 

I'm not sure how that would pan out.

**Comment by agustif** [comment]
We could build some kind of struct that gives an estimation of probability of the torrent being everyone of our current -options-

We then could start with very strong tresholds for categorizing or tagging, and tunning it as we see fit. Different ranges could be directly tagged, put on a line for (admin or user) moderation, and discard the low values into an =Other= bucket (Which could be reanalyzed where we to add a new kind of tag category based on new rules.

besides filename filesize can also help detect whats what, also the source of the torrent (EZTV torrents will always be somewhat TV related even if not only tv-shows per-se


I've also used this on sh scripts in the past https://pypi.python.org/pypi/guessit

It has an option to guess only by filename we could leverage, and it would extract data for us that would make it easier later to relate to TMDb API via search.

**Comment by agustif** [comment]
Could we actually -download- only .torrent files from peers discovered via magnet and use the info from the torrent file like filesize and filenames dirstructure etc

The size of torrent files shouldn't be that big, and could be placed in some tmp folder and discarded after saving the important data in the database.

What do you think?

**Comment by sergiotapia** [comment]
We could definitely download and examine the .torrent file, I imagine there's libs for that. I'm not familiar with the format of the file, does it include all the information you mentioned?

Seems really doable and useful for users.

**Comment by agustif** [comment]
It seems all the info we need can be extracted from the INFO_HASH, I dont know if we need to connect with peers to get that. there are services like http://itorrents.org/ btcache or torcache that cache torrents and let you download from their websites if you provide the info hash (No search or discover features) 


http://stackoverflow.com/questions/28348678/what-exactly-is-the-info-hash-in-a-torrent-file

**Comment by agustif** [comment]
Also there's a Firefox called Magrent extension which seems to solve this, not sure what it does but examining its dependencies or code could help our cause.

Magrent converts magnet links and torrent hashes to torrent files. It uses torrent storage services like Torrage.com for downloading torrent files.
https://addons.mozilla.org/en-US/firefox/addon/magrent/?src=cb-dl-updated

**Comment by agustif** [comment]
https://github.com/killwing/magnet2torrent

This lib tries to match a magnet/info hash to one of the forementioned cache services. It's basically not working on some torrents I tried, but it seems very simple, it tries to go and fetch a url of the like https://cacheservice.ltd/TORRENT_INFO_HASH.torrent. if it isn't successful it tries on another cache service.

Maybe we should be creating a new controller for cache services, and have a first logic step of trying and downloading the torrent file from them, or if that one fails, go ahead and try downloading ourselves the file via local-machine (even maybe upload it back to those cache services)

I dont know, just my 2 cents on the matter.

**Comment by agustif** [comment]
An example even if failed from the lib 

```
➔ magnet2torrent "magnet:?xt=urn:btih:ff5840df343bfe132179c99a735bb7e68943e764&dn=Game.of.Thrones.S05E07.720p.HDTV.x264-0SEC.mkveztv16-09-11&tr=udptracker.coppersurfer.tk80&tr=udpglotorrents.pw6969announce&tr=udptracker.leechers-paradise.org6969&tr=udptracker.opentrackr.org1337announce&tr=udpexodus.desync.com6969"
Get torrent from: http://bt.box.n0808.com/FF/64/FF5840DF343BFE132179C99A735BB7E68943E764.torrent
{ [Error: connect ECONNREFUSED 125.39.36.81:80]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '125.39.36.81',
  port: 80 }
Get torrent from: https://torrage.com/torrent/FF5840DF343BFE132179C99A735BB7E68943E764.torrent
{ [Error: self signed certificate] code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
Get torrent from: http://torcache.net/torrent/FF5840DF343BFE132179C99A735BB7E68943E764.torrent
{ [Error: getaddrinfo ENOTFOUND torcache.net torcache.net:80]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'torcache.net',
  host: 'torcache.net',
  port: 80 }
Failed to get torrent: All services tried.
```

**Comment by SoreGums** [comment]
You could get the .torrent from peers then you would know if a swarm is active/healthy/unhealthy/etc and could record that. Once you have the .torrent file contents, extract the info then discard the torrent file (or never write it to disk in the first place - Jose's DelayedTask prototype from the London meet up would seem like a good fit. Fill a table/record up hashes & blobs, then process them, once done delete). 

My plan is to do what your doing except just crawl the DHT. Spawn VPS's around the planet for a couple days a month to update stats about swarm health. Keep a couple running all the time. Vultr/Digital Ocean are particularly good candidates for this as they have POP's in different places.

**Comment by thangngoc89** [comment]
We can hit zooqle's API for this https://zooqle.com/help/api.html

**Comment by sergiotapia** [comment]
While this is a good idea, it doesn't seem like something I would be able to dedicate the resources to implement. I'm closing this ticket for now
