### ISSUE TITLE
Wiki overhaul

### ISSUE THREAD

**Issue by pahakalle** [sergiotapia/magnetissimo#123]
#### Currently the wiki has instructions for the following operating systems :
(Do we need all of them? Can they be merged?)
- CentOS 7 (Is it working/up to date?)
- Debian 7  (Is it working/up to date?)
- Heroku (#122 )
- Local  (Is it working/up to date?)

#### What new Operating systems should have install/use instructions?
- [ ] VPS (#121)
- [x] Ubuntu/Ubuntu server?
- [ ] FreeBSD
- [ ] Docker

**Comment by tchoutri** [comment]
I'd perhaps suggest adding FreeBSD (and I can directly contribute to that one).  
Moreover, I do think that we need to support the installation guides for a variety of platforms, as well as a docker image for unsupported systems.

**Comment by pahakalle** [comment]
How up to date is the [Future features](https://github.com/sergiotapia/magnetissimo/wiki/Future-Features) section of the wiki?

**Comment by tchoutri** [comment]
There was even a regression on that part, because there used to be a category field in registered magnet links. So I think it has become more relevant than ever.

**Comment by sergiotapia** [comment]
Hi everyone, thanks for your patience while I cleaned up some crust around the old project. Some features have been disabled while I normalize some data from RSS feeds (yay we're using RSS now!) like NSFW and Categories. 

We're leveraging genserver a little simpler now I think, using latest and greatest phoenix/elixir. We also have a discord where we can talk features, bugs, etc in a more casual setting. People love Discord now, I know I do

https://discord.gg/CFtGUaW

Right now a user and I are debugging running the app on Ubuntu, and we're updating the Ubuntu docs with new information including running the application in production mode. I believe the old docs just had it run on `dev` mode.

**Comment by sergiotapia** [comment]
Also, pinky promise no more rewrites hahahaha - the codes in good shape now to build up on.

**Comment by sergiotapia** [comment]
Hi @pahakalle I created a new Ubuntu wiki page: https://github.com/sergiotapia/magnetissimo/wiki/Usage:-Ubuntu-18.04
