### ISSUE TITLE
everything on nyaa pantsu says 0 for everything and filesize

### ISSUE THREAD

**Issue by MoptopX** [sergiotapia/magnetissimo#131]
On nyaa pantsu there are 0's where data should be, on nyaa and nyaa pantsu the filesize says 0.

**Comment by skwerlman** [comment]
This is because the RSS feed provided by nyaapantsu doesn't include that information, so we can't scrape it without a _lot_ of extra complexity.

**Comment by sergiotapia** [comment]
Nyaa pantsu is dead unfortunately, but the overhaul I'm doing solves this problem for Nyaa. We're properly crawling seeders, leechers and sizes now (in bytes!). https://github.com/sergiotapia/magnetissimo/blob/liveview-rewrite/lib/magnetissimo/crawlers/nyaa.ex#L53
