### ISSUE TITLE
Stall after running

### ISSUE THREAD

**Issue by NunoHiggs** [sergiotapia/magnetissimo#15]
Hello,

Thanks for your wonderful product. It appears that i've hit a snag,
After running the application form 2 or 3 days it enters a loop just showing this message:

warning: Float.to_string/2 is deprecated, use :erlang.float_to_binary/2 instead
  (elixir) lib/float.ex:225: Float.to_string/2
  (exq) lib/exq/redis/job_queue.ex:131: Exq.Redis.JobQueue.scheduler_dequeue/2
  (exq) lib/exq/scheduler/server.ex:68: Exq.Scheduler.Server.dequeue/1
  (exq) lib/exq/scheduler/server.ex:56: Exq.Scheduler.Server.handle_info/2
  (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4

If i restart the binary (mix phoenix.server) it restarts indexing correctly.

I've tested this on a VM and a Container... the errors are the same.

Is there a problem or am i doing something wrong?

**Comment by sergiotapia** [comment]
Hi @NunoHiggs I'll run some tests and see what's up - this is strange.

**Comment by sergiotapia** [comment]
This no longer applies, we're not using Exq or Redis. 🚀 Just plain old Erlang queues.
