### ISSUE TITLE
cookie store expects conn.secret_key_base to be at least 64 bytes

### ISSUE THREAD

**Issue by rozatoo** [sergiotapia/magnetissimo#155]
Getting this error when using a secret key below 64 bytes. Since the docker-compose.yml says ``You should change this to a random 32 to 64 character string`` I believe this is a bug

Another issue I'm having once I set a 64 character string is:
![image](https://user-images.githubusercontent.com/69800109/232108569-4a3f793d-e512-4035-9855-1311d4717013.png)

When opening the it shows that the web socket connection is returning 403 Forbidden.

I am using Docker Desktop on Windows

**Comment by sergiotapia** [comment]
@rozatoo That key is usually generated using `mix phx.gen.secret`. 

https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Secret.html

Someone suggested you can also use openssl - did you try that?

`openssl rand -base64 48`

If this works for you, I should edit the docker-compose.yml comment to be explicit about using the openssl command or the mix phx.gen.secret command.

**Comment by rozatoo** [comment]
When I used

``openssl rand -base64 32``

it did not work but when I used

``openssl rand -base64 64``

it did

**Comment by sergiotapia** [comment]
Interesting, I'll update the comment then, thanks for reporting this.
