### ISSUE TITLE
Guide/ Tutorial / Documentation in creating new parsers.

### ISSUE THREAD

**Issue by agustif** [sergiotapia/magnetissimo#16]
Hi, after helping with EZTV I was thinking of helping on another new integration, and being honest I don't even remember what I did (lol). So I'm thinking to repeat the process and document it in a Example/Wiki/Blogpost fashion. Maybe it helps to get more contributors to push PR with new sites.

Anything of the like already exists? Should I pursue this myself?

Thanks!

**Comment by sergiotapia** [comment]
Hey @agustif - thanks again for the EZTV integration. I think I know how the process works on Github now, you just fork the project and work on what you need then request a pull request then I can confirm merge from my end. 

A wiki page document on how to create a new integration would be awesome, I'm sure lots of people would find it useful. 💪 So maybe write it in a gist, and I can create it on the wiki for the project.

Let me know if you need anything.

**Comment by agustif** [comment]
Yes, you can help contributors while they have an opened PR and a history is created with comments and commits, really useful for collaboration!

I will go on and try and do a new integration. Im thinking of some non-english site to add more diversity to the scrapers, what do you think?

**Comment by sergiotapia** [comment]
@agustif That's fine sure. The app has utf-8 support for korean/chinese/etc names would work just fine.

**Comment by markman123** [comment]
Started on this https://gist.github.com/markman123/e37d2197e8455d81ab794f12ef63aef0

Are you still maintaining this repo?

**Comment by sergiotapia** [comment]
@markman123 I actually have a rewrite in the work with a much simpler code structure. No more redis dependency for example. If you write a new parser I'll move it over to the new structure lickety split.

**Comment by sergiotapia** [comment]
@markman123 Rewrite is up on Github live, check out example implementations under the `crawler` folder for inspiration. Thanks for the help! Appreciate it
