### ISSUE TITLE
Add *arr integration guide to README

### ISSUE THREAD

**Issue by ldexterldesign** [sergiotapia/magnetissimo#162]
👋

Thanks for useful software!

Apologies for brevity

If some info existed relating to integration with *arr (i.e. prowlarr > lidarr/radarr/sonarr) then I'd feel better about attempting that task (I did try with prowlarr and sonarr but failed, a bit lost..?) 🙏

Yours hopefully

**Comment by askiiart** [comment]
I believe the Torznab API isn't done yet, but I may be wrong. Check out issue #56 for status updates.

**Comment by ldexterldesign** [comment]
👌
