### ISSUE TITLE
Feature request: Use git tags to created tagged releases using Semantic Versioning

### ISSUE THREAD

**Issue by loganmarchione** [sergiotapia/magnetissimo#163]
Currently, there is only [one tagged release](https://github.com/sergiotapia/magnetissimo/tags) of magnetissimo, which is `1.0-final` from 2018.

I see that you recently setup GitHub Actions to publish [container images to GHCR](https://github.com/sergiotapia/magnetissimo/pkgs/container/magnetissimo), which is great (no more building the app)! However, these images are built from `master`, so there is no way to tell what "version" of the app I'm running, or if an upgrade is a major, minor, or patch upgrade.

Ideally, you'd [tag](https://initialcommit.com/blog/git-tag) releases with a [semantic version](https://semver.org/), like `1.2.3`. This has a couple benefits:

- Users would know what "version" of the application they're running (e.g., `1.2.3`)
- Users would know that upgrading from `1.2.3` to `1.2.4` is a small change, but `1.2.3` to `2.0.0` is a large change that could potentially cause problems
- Dependency management tools like Dependabot or [Renovatebot](https://docs.renovatebot.com/docker/) can use the `1.2.3` tag to automatically upgrade to a new version like `1.2.4` (based on user-defined rules)

You'd have to tweak the GitHub Action file to run on tags instead of pushes to master, and you'd also have to include the tag in the image name (like `ghcr.io/sergiotapia/magnetissimo:1.2.3`).

```
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
```

You could still keep the `master` or `latest` tag that is built from `master` for users wanting to test.

**Comment by sergiotapia** [comment]
This is a wonderful idea, I would love to make this a reality! I'll add it to our Milestone list for Delicioso (3.0)

**Comment by sergiotapia** [comment]
That was pretty painless. We now build images on:

```
on:
  push:
    branches: 
      - master
      - delicioso
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
```
