### ISSUE TITLE
Add scraper for books (libgen)

### ISSUE THREAD

**Issue by agustif** [sergiotapia/magnetissimo#17]
Would be cool to scrap libgen, it has a latest endpoints we can paginate on and also gives magnet links to torrent downloads of files, might be worth a look on

**Comment by sergiotapia** [comment]
Good idea! What's the root url? I can add a scraper for it.

**Comment by agustif** [comment]
Libgen.io

**Comment by sergiotapia** [comment]
Are these the page URL's we need to hit?

```
http://libgen.io/search.php?mode=last&view=simple&phrase=1&timefirst=&timelast=&sort=def&sortmode=ASC&page=1
http://libgen.io/search.php?mode=last&view=simple&phrase=1&timefirst=&timelast=&sort=def&sortmode=ASC&page=2
http://libgen.io/search.php?mode=last&view=simple&phrase=1&timefirst=&timelast=&sort=def&sortmode=ASC&page=3
http://libgen.io/search.php?mode=last&view=simple&phrase=1&timefirst=&timelast=&sort=def&sortmode=ASC&page=4
http://libgen.io/search.php?mode=last&view=simple&phrase=1&timefirst=&timelast=&sort=def&sortmode=ASC&page=5
```

With `page` at the end there, changing?

**Comment by agustif** [comment]
yes, they are, we have a last-modified instead of last-added endpoint, not sure what would be best.

**Comment by sergiotapia** [comment]
I think latest added is best. I can't seem to find magnet links anywhere though. Are you sure they offer that? I checked about 10 different book links.

**Comment by agustif** [comment]
You're totally right, on mirror [1] you can download but it generates a torrent file calling a php with a MD5, not sure if that could be use to call torcache and the like or what... Sorry for the misslead

**Comment by agustif** [comment]
I've remembered about this, though: http://libgen.io/repository_torrent/

**Comment by sergiotapia** [comment]
So it looks like there is no magnet link, no?

**Comment by agustif** [comment]
Nope, only torrent files available as batch download.

**Comment by markman123** [comment]
We could get the torrent and convert it to a magnet... I wonder if you can do that in memory or if it requires a download? Also, that's probably worthwhile as its own extension which could be brought in here as a dep?

**Comment by agustif** [comment]
http://torrent2magnet.com/

https://github.com/ungoldman/magnet-link

**Comment by agustif** [comment]
Hey , so libgen magnet URI's are listed on a .txt endpoint

http://libgen.io/repository_torrent/magnet-links.txt

**Comment by sergiotapia** [comment]
Circling back to this one, I'm not going to be able to do anything crazy in the near-future. Just magnet scraping. Going to close the ticket.
