### ISSUE TITLE
Category of the torrent

### ISSUE THREAD

**Issue by Gank** [sergiotapia/magnetissimo#18]
Just an idea,

Most of the websites include the category of the torrent, wouldn't it be interesting to store the category in the database for filtering in the search, etc ?

Great project, Thanks!

**Comment by sergiotapia** [comment]
Great idea, I'll definitely figure out a way to "normalize" all the different categories into fewer options within Magnetissimo.

**Comment by sergiotapia** [comment]
Circling back to this, we won't offer any categories in the near-future.
