### ISSUE TITLE
Landing page only.

### ISSUE THREAD

**Issue by ndragon798** [sergiotapia/magnetissimo#23]
The only thing I get when I go to localhost:4000 is the landing page.

Centos7 followed the guide word for word.

**Comment by farfeduc** [comment]
I have the same issue, did you solve it ?

For now it only displays : "This is the landing page.".

Maybe we need to start it in production mode. I'll try tomorrow.

**Comment by farfeduc** [comment]
You need to go to /browse but the app shutdowns after 1hour or so :/

**Comment by ndragon798** [comment]
I ended up switching back to bitcannon sadly. I will try again with this today.

**Comment by ndragon798** [comment]
Okay just got it up and running will report back in hour maybe 2.

**Comment by ndragon798** [comment]
Left it on over night and it didn't shutdown maybe try reinstalling?
