### ISSUE TITLE
Should I add streaming to the project?

### ISSUE THREAD

**Issue by sergiotapia** [sergiotapia/magnetissimo#25]
I know, I know - streaming is bad for healthy torrents. But that was back in 2007, these days the swarm is gigantic.

Should I add in a button people can click and stream the content in their browser?

I imagine this would only work for torrents that have 1 file, and a playable file at that.

I could probably get in touch with a streaming service and ask them if they can help out, for example: https://instant.io/

It uses WebRTC so the traffic is peer to peer. Hm... food for thought.

**Comment by SoreGums** [comment]
And instant.io uses https://github.com/feross/webtorrent just go direct :)

**Comment by thangngoc89** [comment]
webtorrent on browser can not communicate with a normal bittorrent client. You need to implement this in the backend

**Comment by sergiotapia** [comment]
The example code for the lib seems like it'll "Just Work(tm)"

```
var WebTorrent = require('webtorrent')

var client = new WebTorrent()
var magnetURI = '...'

client.add(magnetURI, function (torrent) {
  // Got torrent metadata!
  console.log('Client is downloading:', torrent.infoHash)

  torrent.files.forEach(function (file) {
    // Display the file by appending it to the DOM. Supports video, audio, images, and
    // more. Specify a container element (CSS selector or reference to DOM node).
    file.appendTo('body')
  })
})
```

**Comment by thangngoc89** [comment]
Yes. It works but it only can find other webrtc peer, not bittorrent peer. I'll find some links for you

**Comment by thangngoc89** [comment]
It's actually in the README https://github.com/feross/webtorrent

> To make BitTorrent work over WebRTC (which is the only P2P transport that works on the web) we made some protocol changes. Therefore, a browser-based WebTorrent client or "web peer" can only connect to other clients that support WebTorrent/WebRTC

**Comment by sergiotapia** [comment]
Ah the devil is in the details. Then it's a no-go.

**Comment by IDerr** [comment]
Why not using something like https://www.npmjs.com/package/torrent-stream ?

**Comment by thangngoc89** [comment]
@IDerr it involes a node.js process and if we have a node,js process, we can just use webtorrent :D

**Comment by chopraaa** [comment]
@thangngoc89 Doesn't require web peers though. Why is a node process an issue?

**Comment by synctext** [comment]
Indeed, Streaming is not bad for swarms.

We have solid code operational for this and it's quite reliable. 

- [Python implementation using Libtorrent and VLC](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Video/VideoServer.py#L61) for smooth streaming in Tribler
- [Android version](https://github.com/javto/Tribler-streaming) without Python
- [Piece picking algorithm dedicated to streaming](http://svn.tribler.org/abc/branches/riccardo/SLaPP/layeredPP.pdf)
- [phd thesis on bittorrent streaming](http://repository.tudelft.nl/islandora/object/uuid:80ebec52-2323-4fe0-bf7e-92b594c03d3f) 
- See our [operational live streaming extension for Bittorrent from 2009](http://www.ds.ewi.tudelft.nl/reports/2009/PDS-2009-002.pdf)

btw, great project people!

**Comment by wow-sweetlie** [comment]
You sould keep with unix philosphy, crawling torrent and streaming video torrent are two very different jobs. The question is more how can things be connected :)

**Comment by tchoutri** [comment]
yeah I agree with @wow-sweetlie, I'm sure we could point to other projects that do the job better than us

**Comment by pahakalle** [comment]
For streaming video we could just point to the webtorrents [desktop](https://webtorrent.io/desktop/) app, tough still in beta its advancing very fastly, looking at the [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop) github page.
And by it having a copy-paste magnet link "option" it will work nicely with this project without added changes (by that i meant no need to add .torrent file creation).

**Comment by sergiotapia** [comment]
Closing this issue as this feature seems out of scope for the project. Plenty of other choices if streaming is your thing.

What I will work on though is endpoints so you can pipe Magnetissimo data into any other project you need to use. JSON format.
