### ISSUE TITLE
Goal 1: No javascript - but requires npm / nodejs to work?

### ISSUE THREAD

**Issue by sammcj** [sergiotapia/magnetissimo#28]
I LOVE goal 1 of no javascript, I went to install then I saw npm install in the instructions, looked into it and indeed it uses nodejs ... JS being javascript.

wat?

**Comment by net** [comment]
I doesn't require nodejs or `npm install`, the install guide is just outdated.

**Comment by olieidel** [comment]
As far as I can see, all JS has been removed in 9784d297cbcfdd8336b2fca23908def190f39e74.

The step  ```npm install``` could therefore be removed from the Wiki (Usage: Local). Correct me if I'm wrong! :)

**Comment by sammcj** [comment]
Yeah that seems to be the general consensus (Which also makes me happy as I really just want to see JS burn...)

I think the quick install doc needs a bit of an update from someone that knows the product, things like minimum requirements etc... and perhaps the rocker method should be the default one now too?

--
Sam

**Comment by sergiotapia** [comment]
Yeah the Wiki does need an update, I nuked JS with that commit. :)
