### ISSUE TITLE
undefined function: Mix.compilers/0

### ISSUE THREAD

**Issue by sammcj** [sergiotapia/magnetissimo#29]
- CentOS 7.3 (all updates installed)
- Elixir 0.12.5.2-el7

```shell
/opt # yum install elixir postgresql96-server
/opt # git clone https://github.com/sergiotapia/magnetissimo.git --depth=1
/opt # cd magnetissimo/
/opt/magnetissimo [0] # mix deps.get

** (UndefinedFunctionError) undefined function: Mix.compilers/0
    (mix) Mix.compilers()
    mix.exs:9: Magnetissimo.Mixfile.project/0
    (mix) lib/mix/project.ex:348: Mix.Project.get_project_config/1
    (mix) lib/mix/project.ex:52: Mix.Project.push/2
    (stdlib) lists.erl:1248: :lists.foldl/3
```

Sorry I'm not sure what other debugging information might be helpful here, if someone can point me in the right direction I can go from there.

**Comment by net** [comment]
Your version of Elixir is severely outdated (latest Elixir is 1.4.1).

**Comment by sammcj** [comment]
Ah ok, that's the current stable version in RHEL/CentOS 7.3.

Ill see if there is an official Elixir supported yum repo and update if you think that's the issue.

Thanks,

--
Sam

**Comment by Oxymoron290** [comment]
What was the resolution for this?

**Comment by aryanjain1242** [comment]
answer mile toh batana
