### ISSUE TITLE
[errors] Usage: Debian 7

### ISSUE THREAD

**Issue by MartinBrugnara** [sergiotapia/magnetissimo#30]
Errors in the [Usage: Debian 7](https://github.com/sergiotapia/magnetissimo/wiki/Usage:-Debian-7) wiki's command examples:

Typos:
```
sudo apt-get install portgresql redis-server nodejs esl-erlang exlixir git screen
```

shall be
```
sudo apt-get install postgresql redis-server esl-erlang elixir git screen
```

Deps error:
_NodeJS_ doesn't seam to be required, at least there is no `package.json` file.

**Comment by sergiotapia** [comment]
Thanks for pointing this out. The Wiki needs to be updated since we're no longer using JS for the project.

**Comment by sergiotapia** [comment]
Done and done!
