### ISSUE TITLE
Add torrent9.biz crawler

### ISSUE THREAD

**Issue by bilyboy785** [sergiotapia/magnetissimo#31]
It's possible to add t411.li and torrent9.biz ?

**Comment by sergiotapia** [comment]
http://www.t411.li/ has no magnet links so I can't add a crawler for it.

http://www.torrent9.biz is doable, they have magnet links. :)

**Comment by sergiotapia** [comment]
Both those sites are now riddled with the bad kind of ads - not going to add them sorry.
