### ISSUE TITLE
Sortable by ...

### ISSUE THREAD

**Issue by kingdonb** [sergiotapia/magnetissimo#36]
Would you consider adding sortability to the fields?  It might be nice to sort searches by number of seeds I'm thinking so that search results with 0 seeds don't clutter up the top of the results listing.

**Comment by sergiotapia** [comment]
I can add that by using hyperlinks for the table header. 

URL would look like: http://localhost:4000?term=foobar&sort=DESC&field=seeders ? Something like that. I'll look into it.

**Comment by kingdonb** [comment]
That was the info I was looking for, I don't know enough about Phoenix to implement it myself without help, but maybe I can send you a PR

**Comment by yaroto98** [comment]
Please do. I just installed this, and that was the first thing I tried to do.

**Comment by kingdonb** [comment]
It would be nice to have some control over the indexing, too... like for example, to put a search query at the front of the queue, so that one does not have to wait for the mirroring to complete in order to find things that are not early in the crawling order.

Maybe something as simple as adding a second queue, that spiders out page results from search queries that are made by the user?

**Comment by tchoutri** [comment]
Closed in favour of [this future feature](https://github.com/sergiotapia/magnetissimo/wiki/Future-Features#sorting-parameters).  
Thanks :)
