### ISSUE TITLE
Make Size Column Human Readable

### ISSUE THREAD

**Issue by yaroto98** [sergiotapia/magnetissimo#37]
Small Feature request. In the UI please make the "Size" column human readable. (KB/MB/GB)

**Comment by sergiotapia** [comment]
@yaroto98 fixed here: https://github.com/sergiotapia/magnetissimo/commit/c0d169fe13bbac99cf1c400732eb7d8579436c3d

![image](https://cloud.githubusercontent.com/assets/686715/22399063/9e73d920-e562-11e6-9421-b593e8a8b2a4.png)
