### ISSUE TITLE
Size Column info on second line

### ISSUE THREAD

**Issue by yaroto98** [sergiotapia/magnetissimo#39]
Small cosmetic issue with the size column. Resulted from the fix of issue #37 

Sometimes when the size of the file exceeds 6 or so characters, the "MB" tag gets put onto a new line. I believe this is due to a hard coded rowsize for the column. Not sure how you want to fix it. Increase column size so it stays on one line, remove numbers after decimal place, or make all columns resize-able in the ui. Though that last one would probably take a lot more work than the others.

![image](https://cloud.githubusercontent.com/assets/13698122/22399309/da795dbe-e567-11e6-8615-58aa72818071.png)

**Comment by sergiotapia** [comment]
Example: 
![image](https://cloud.githubusercontent.com/assets/686715/22399312/e18d70d6-e567-11e6-8ba4-ce85801eb43a.png)

I'll fix this cosmetic issue

**Comment by kingdonb** [comment]
& nbsp; is the easiest solution

**Comment by sergiotapia** [comment]
Fixed in https://github.com/sergiotapia/magnetissimo/commit/2581d1fecfaeb51aaeb316631a33ba26867bec71
