### ISSUE TITLE
Update Heroku documentation

### ISSUE THREAD

**Issue by benfb** [sergiotapia/magnetissimo#42]
I recently deployed magnetissimo to Heroku and wrote up the steps:

# Run it on Heroku

To run it on Heroku, you need to:

Clone the git repository from Github:

```
$ git clone git@github.com:sergiotapia/magnetissimo.git
$ cd magentissimo
```

Create the Heroku application using the Elixir build pack.

```
$ heroku create --buildpack "https://github.com/HashNuke/heroku-buildpack-elixir.git"
Creating mysterious-meadow-6277... done, stack is cedar-14
Buildpack set. Next release on mysterious-meadow-6277 will use https://github.com/HashNuke/heroku-buildpack-elixir.git.
https://mysterious-meadow-6277.herokuapp.com/ | https://git.heroku.com/mysterious-meadow-6277.git
Git remote heroku added
```

Create the Postgres database using the Heroku free plan:

```
$ heroku addons:create heroku-postgresql:hobby-dev
```

Generate a secret key for the project:

```
$ mix deps.get
$ mix phoenix.gen.secret
xvafzY4y01jYuzLm3ecJqo008dVnU3CN4f+MamNd1Zue4pXvfvUjbiXT8akaIF53
```

Add the following environment variables, including the previously generated key:

```
$ heroku config:set POOL_SIZE=18
$ heroku config:set SECRET_KEY_BASE=xvafzY4y01jYuzLm3ecJqo008dVnU3CN4f+MamNd1Zue4pXvfvUjbiXT8akaIF53
```

Edit `config/prod.exs`:

Add `secret_key_base: System.get_env("SECRET_KEY_BASE")` to the `Magnetissimo.Endpoint` block.

Add a block for configuring the production database:

```elixir
config :magnetissimo, Magnetissimo.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true
```

Comment out `import_config "prod.secret.exs"`.

Add a file called `Procfile` in the directory root with the following contents:

```
web: MIX_ENV=prod mix phoenix.server
```

Commit your changes:

```
$ git add .
$ git commit -am "deploy to heroku"
```

Deploy the app:

```
$ git push heroku master
```

Configure the database:

```
$ heroku run "POOL_SIZE=2 mix ecto.migrate"
```

I'm not sure what the best way is to merge these changes into the wiki, so I'm posting them here for now.

**Comment by benfb** [comment]
I also wonder if it would be possible to support a deploy to Heroku button to streamline this process, but this is suitable for now.

**Comment by sergiotapia** [comment]
#43 added a Heroku Deploy button, can you give it a shot and see if it solved your issue?

**Comment by mnpenner** [comment]
The button worked for me.

**Comment by sergiotapia** [comment]
Thanks for confirming @mnpenner appreciate the second eyes. :)
