### ISSUE TITLE
eztv crawler is crashing the application after some time

### ISSUE THREAD

**Issue by lavalampa** [sergiotapia/magnetissimo#49]
After running magnetissimo for some time the application crashes, it is caused by the eztv crawler.
I have screenshot of it when it happend:
[https://i.imgur.com/JMh01i5.png](https://i.imgur.com/JMh01i5.png)

**Comment by yaroto98** [comment]
Looks like the same issue as #34

**Comment by sergiotapia** [comment]
Thanks for reporting this @lavalampa I'll take a look.

**Comment by sergiotapia** [comment]
This is fixed in #72 - should be landing soon. :)
