### ISSUE TITLE
Search capabilities need to be expanded

### ISSUE THREAD

**Issue by yaroto98** [sergiotapia/magnetissimo#54]
When searching for a tv episode using the typical nomenclature (example: "Magicians s02e01") doesn't catch all the results it should. I believe this is because the search is looking for the exact string entered, not performing a proper search of multiple strings. The example "Magicians s02e01" won't hit on "Magicians US s02e01" because of the "US".

Example of searching just "Magicians" so you can see all the available s02e01 torrents.
![screenshot from 2017-01-30 08-35-48](https://cloud.githubusercontent.com/assets/13698122/22425088/72fb402e-e6c7-11e6-9d75-9f4480e8ff17.png)

Results of searching "Magicians s02e01"
![screenshot from 2017-01-30 08-39-41](https://cloud.githubusercontent.com/assets/13698122/22425154/c1b30076-e6c7-11e6-8222-eee5fa546796.png)

**Comment by sergiotapia** [comment]
Yes, right now we're matching on the entire string.


```
results =
      from t in Torrent,
      where: ilike(t.name, ^"%#{params["term"]}%"),
      order_by: [desc: :inserted_at]
```

I'll tweak it. I think I'll have to split the term on space, and add multiple where statements. We'll see.

**Comment by yaroto98** [comment]
Yea, that's probably the quickest and easiest way to do it. Alternatively we could set up Full Text Search for that field. It'd be more setup, but probably a lot easier to maintain in the long run.

**Comment by trigun0x2** [comment]
Have you guys taken a look at `fuzzystrmatch` and `pg_trgm`?

**Comment by Elly6** [comment]
Can we change the "inserted_at" variable to something else? What other sorting options are available? I'm trying to show most seeded torrents at top.
https://github.com/sergiotapia/magnetissimo/issues/36

**Comment by yaroto98** [comment]
If you replace "inserted_at" with "seeders" you will show most seeded torrents at top.

**Comment by sergiotapia** [comment]
I'll add sortable table headers tonight so you'll be able to sort within the app itself, ez-pz. :)

**Comment by tchoutri** [comment]
Closed in favour of [this future feature](https://github.com/sergiotapia/magnetissimo/wiki/Future-Features#full-text-search). It's in the pipeline :)
