### ISSUE TITLE
Unable to get magnetissimo running locally

### ISSUE THREAD

**Issue by heronblade** [sergiotapia/magnetissimo#55]
I wasn't able to get magnetissimo up and running locally, until I added a few steps.  You have to have postgres up and running.  I wasn't able to make an update to the wiki.  I cloned it, and made the update locally. Let me know if this works for you.

# Run it locally

To run Magnetissimo locally, you need to have Elixir and Postgresql installed. 

Install Elixer

`brew update`

`brew install elixir`

Install Postgresql

`brew install postgres`

To start Magnetissimo locally:

  * Install dependencies with `mix deps.get`
  * Edit `dev.exs` and set your database username and password (see example below).
  * Start postgres `pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start`
  * Create and migrate your database with `mix ecto.create && mix ecto.migrate`
  * Start Phoenix endpoint with `mix phoenix.server`
  * Now you can visit [`localhost:4000`](http://localhost:4000) from your browser.

```
# Configure your database inside config/dev.exs
config :magnetissimo, Magnetissimo.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "magnetissimo_dev",
  username: "CHANGEME",
  password: "CHANGEME",
  hostname: "localhost",
  port: 5432,
  pool_size: 50
```

**Comment by sergiotapia** [comment]
Thanks, I've updated the Local Usage wiki page based on your suggestions. 🚀
