### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by Elly6** [sergiotapia/magnetissimo#57]
Thank you for creating magnetissimo!

Several questions:

1. How can I omit several searches without breaking functionality? I only want to crawl thepiratebay and extratorrents.

2. Could I modify thepiratebay or demonoid crawlers to use their tor .onion domains? If I were using a transparent proxy, would the crawl tell the difference?

3. Is it possible to stop the magnetissimo from saving magnets with 0/0 seeds/leechers? I would prefer to only store torrents that have x amount of seeds. If so, how to?

4. How can I organize the main page so that it shows the most seeded torrents at the top?

5. Could these torrent sites easily block your crawler or define this type of activity as malicious/abusive?

**Comment by yaroto98** [comment]
I'm by no means a pro at this, but here's my 2 cents:

1. Grepping through the code it looks like you only need to go to lib/magnetissimo.ex and comment out the crawlers you don't want lines ~16-22. You'll see Demonoid commented out already.

2. Probably. give it a try. go to lib/crawler/thepiratebay.ex and modify every URL you see there let us know how it goes! As for the transparent proxy, I doubt the crawler would tell the difference.

3. Of course it's possible, dive into the code and figure it out! Maybe even set up a config variable. If you really don't like them you can always just run a delete statement on the db to periodically clean them out.

4. Work in progress see issue #36 

5. Absolutely. Rargb.to has already contacted us and asked us to use their API and not the generic scraper. But if we use the API they're happy to serve up the data.

**Comment by Elly6** [comment]
@yaroto98

Hey thank you so much for your response!

"3. Of course it's possible, dive into the code and figure it out! Maybe even set up a config variable. If you really don't like them you can always just run a delete statement on the db to periodically clean them out."

As I don't actually know how to code in elixir (hence my stupid questions above) I had hoped omitting 0/0 torrents would be as simple as commenting out a line or modifying one or two lines.

**Comment by yaroto98** [comment]
Yea, I don't know Elixir either. However, I did find the line you're looking for:

web/models/torrent.ex
line number 25:
    |> validate_number(:seeders, greater_than_or_equal_to: 0)
Increase that 0 to whatever you want. Same for leechers on the next line.

**Comment by Elly6** [comment]
Amazing. Thank you so much!
