### ISSUE TITLE
Support for Torrentz2 request

### ISSUE THREAD

**Issue by Elly6** [sergiotapia/magnetissimo#58]
Support for either of these sister sites would be extraordinary:

https://torrentz2.eu
https://torrentproject.se

or

http://torrentzwealmisr.onion
http://x4torrentjjjjuxy.onion

**Comment by sergiotapia** [comment]
Thanks, I'll make some crawlers for those sites.

**Comment by tchoutri** [comment]
Torrentz2 doesn't provide an RSS feed / API but we can iterate over the last twenty pages with `https://torrentz2.eu/search?f=&p=1..20`

**Comment by pahakalle** [comment]
The issue with torrentz2 is that there are "many" (look and seems to be all new ones) torrent's there with no links (to websites) and it doesn't offer magnet links so is there a use for crawling it?

**Comment by tchoutri** [comment]
We actually can build magnet links from this: 
![capture du 2018-01-09 16-14-10](https://user-images.githubusercontent.com/15848443/34727802-41f20364-f558-11e7-85ba-c9d8e455b77b.png)

But I agree, for now it's not very useful.
