### ISSUE TITLE
error trying to compile

### ISSUE THREAD

**Issue by bluescreeny** [sergiotapia/magnetissimo#6]
Installed all of the dependencies, and tried to run the command "mix ecto.create && mix ecto.migrate"
I'm assuming I need to change something in the config file?

![2a6790a3785c4606bfd3086ff6c9def7](https://cloud.githubusercontent.com/assets/7502322/17475778/5c22e636-5d65-11e6-8c64-24fe4ee42a1e.png)

Generated magnetissimo app
** (Mix) The database for Magnetissimo.Repo couldn't be created: an exception was raised:
    ** (KeyError) key :password not found in: [types: true, username: "root", backoff_type: :stop, pool: DBConnection.Connection, database: "template1stname: "localhost", pool_size: 10]
        (elixir) lib/keyword.ex:333: Keyword.fetch!/2
        (postgrex) lib/postgrex/protocol.ex:444: Postgrex.Protocol.auth_md5/4
        (postgrex) lib/postgrex/protocol.ex:361: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:623: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

09:33:32.067 [error] GenServer #PID<0.3633.0> terminating
** (KeyError) key :password not found in: [types: true, username: "root", backoff_type: :stop, pool: DBConnection.Connection, database: "template1", ome: "localhost", pool_size: 10]
    (elixir) lib/keyword.ex:333: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:444: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:361: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:623: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

**Comment by sergiotapia** [comment]
Yeah you need to set the username and password for your Postgres installation.

Set it right here:

https://github.com/sergiotapia/magnetissimo/blob/master/config/dev.exs#L37

Let me know if it works out.

**Comment by bluescreeny** [comment]
Sorry, but am I just blind or something? Which one of these are supposed to be the username and password?
![9e867ffc27434f7c92bab71dc635dfcb](https://cloud.githubusercontent.com/assets/7502322/17490264/b0120f3e-5daa-11e6-9c7d-cc192f42cce4.png)

**Comment by sergiotapia** [comment]
It should look something like this:

```
# Configure your database
config :magnetissimo, Magnetissimo.Repo,
  username: "foobar",
  password: "barbaz",
  adapter: Ecto.Adapters.Postgres,
  database: "magnetissimo_dev",
  hostname: "localhost",
  pool_size: 10
```

**Comment by sergiotapia** [comment]
@bluescreeny let me know if that worked out for you, thanks!

**Comment by TehNut** [comment]
I was having the same issue, so I'll try myself in a bit.

**Comment by bluescreeny** [comment]
It compiles, but can't start the server for some reason. Can't be bothered to look into it right now.

**Comment by TehNut** [comment]
Compiled and started just fine for me. I must say, this is quite fast. 200 pages in ~5 minutes

**Comment by sergiotapia** [comment]
Well if you're feeling up to it, circle back with more info @bluescreeny thanks

**Comment by bluescreeny** [comment]
Does this reopen it?

When typing in the command "mix phoenix.server" it gives me this error. I'm confident I installed redis, both through the "would you like to install redis" option and manually just now. (i hate node..)
![screenshot_17](https://cloud.githubusercontent.com/assets/7502322/17526667/e726199a-5e70-11e6-9e54-ab828a0f6464.png)
![screenshot_18](https://cloud.githubusercontent.com/assets/7502322/17526673/eaa30ce0-5e70-11e6-820c-1d2ffe2d05cf.png)

**Comment by sergiotapia** [comment]
This isn't really a problem with Magnetissimo, but a problem with your connection configuration. Make sure you set the right username and password to connect it to.
