### ISSUE TITLE
Database Maintenance

### ISSUE THREAD

**Issue by Elly6** [sergiotapia/magnetissimo#62]
Occasionally uploaders on torrentdownloads or thepiratebay will submit torrents with 9000+ or even 20,000+ seeders. These torrents are labelled to appear legitimate but contain malware.

I'm curious to know how you might handle scrubbing the database of fake/spam torrents? Through postgres? Command line? Or modifying magnetissimo to ignore fake torrents altogether?

**Comment by sergiotapia** [comment]
We can set a threshold and ignore those torrents that have an obscene amount of seeders/leechers.

Can you provide some screenshot examples? Thank you :)

**Comment by Elly6** [comment]
Assigning a threshold (9,000+ seeders for example) could unintentionally omit legitimate torrents. 

Fake torrents:
![magnetissimo1](https://cloud.githubusercontent.com/assets/25473187/22593666/9e602cfe-ea17-11e6-9d4a-716316d342f9.png)

Legit torrents:
![magnetissimo2](https://cloud.githubusercontent.com/assets/25473187/22593678/ae433b84-ea17-11e6-8c82-204ebb908982.png)

**Comment by sergiotapia** [comment]
@Elly6 Circling back to this issue after a few months - I'm not sure there's an easy way to detect whether a torrent is fake or not. Do you have any ideas?

**Comment by jspraul** [comment]
https://torrentfreak.com/btdigg-shut-down-due-to-torrent-spam-for-now-160711/

https://BTDigg.com is back (maybe?) after promising "When we finish creating an AI that filters spam, we’ll reopen the site."
