### ISSUE TITLE
[info] Application magnetissimo exited: shutdown

### ISSUE THREAD

**Issue by nxtreaming** [sergiotapia/magnetissimo#63]
I faced many times: "[info] Application magnetissimo exited: shutdown"

Reason: ** (WithClauseError) no with clause matching

The debug Log：

[error] GenServer #PID<0.1460.0> terminating
** (WithClauseError) no with clause matching: {:ok, %HTTPoison.Response{body: "\n<!DOCTYPE html>\n<html>\n<head lang=\"en\">\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n<meta name=\"author\" content=\"World Wide Torrents\"/>\n<meta name=\"generator\" content=\"World Wide Torrents\"/>\n<meta name=\"description\" content=\"WorldWide Torrents Community, A place to download TV series, movies, music, games torrents, make friends and to have fun, A Place to call home\"/>\n<meta name=\"keywords\" content=\"torrents, worldwide torrents, WWRG, WWT, torrents download, browse torrents, search torrents, best torrent site, fast torrent download, safe torrents, Movie torrents, TV torrents, Ebook torrents, Music Torrents, Games Torrent, kat alternative, torrentz alternative,\"/>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"themes/Final/css/w3.css\"/>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"themes/Final/css/w3-theme.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"themes/Final/css/glyphicons.css\"/>\n<link rel=\"shortcut icon\" href=\"/themes/NB-TT-2c/images/favicon.ico\"/>\n<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css\">\n<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Allerta+Stencil\">\n<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Tangerine\">\n<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Josefin+Sans\">\n<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>\n<link href=\"https://fonts.googleapis.com/css?family=Lora\" rel=\"stylesheet\">\n<script type=\"text/javascript\" src=\"/backend/java_klappe.js\"></script>\n<style>.w3-allerta{font-family:\"Allerta Stencil\",Sans-serif;}.w3-tangerine{font-family:'Tangerine',serif;font-size:48px;}.w3-jose{font-family:'Lora',serif;font-style:normal;font-weight:800;src:local('Josefin Sans'),local('JosefinSans'),url(https://fonts.gstatic.com/s/josefinsans/v9/xgzbb53t8j-Mo-vYa23n5j0LW-43aMEzIO6XUTLjad8.woff2) format('woff2');unicode-range:U+0100-024F,U+1E00-1EFF,U+20A0-20AB,U+20AD-20CF,U+2C60-2C7F,U+A720-A7FF;}.fix-header{list-style-type:none;margin:0;padding:0;background-color:#333;position:fixed;top:0;width:100%;}</style>\n<title>WorldWide Torrents : Browse Torrents</title>\n</head>\n<body>\n \n<div class=\"w3-top w3-card-8\">\n<ul class=\"w3-navbar w3-theme-d2 w3-left-align w3-large\">\n<li class=\"w3-hide-medium w3-hide-large w3-opennav w3-right\">\n<a class=\"w3-padding-large w3-hover-white w3-large w3-theme-d2\" href=\"javascript:void(0);\" onclick=\"openNav()\"><i class=\"fa fa-bars\"></i></a>\n</li>\n<li><a href=\"/index.php\" class=\"w3-padding-large w3-theme-d4 w3-allerta\"><img src=\"https://cdn.pximg.xyz/2a8869edc0138774cd01cd3a17b56d89.png\" height=\"26\" width=\"26\">&nbsp;WorldWide Torrents</a></li>\n<li class='w3-hide-small w3-right'><a href=\"/account-login-signup.php\">Login/Sign Up</a></li> <li class=\"w3-hide-small w3-dropdown-hover\"><a href=\"/forums.php\" class=\"w3-padding-large w3-hover-white\" title=\"FORUMS\"><i class=\"fa fa-comments\"></i> Forums</a>\n<div class=\"w3-dropdown-content w3-white w3-card-4 w3-small\">\n<a href=\"/faq.php\"><i class=\"fa fa-question\"></i> FAQ</a>\n<a href=\"/rules.php\"><i class=\"fa fa-sitemap\"></i> Rules</a>\n<a href=\"/memberlist.php\"><i class=\"fa fa-users\"></i> Members</a>\n</div>\n</li>\n<li class=\"w3-hide-small w3-dropdown-hover\"><a href=\"#\" class=\"w3-padding-large w3-hover-white\" title=\"Torrents\"><i class=\"fa fa-anchor\"> Torrents</i></a>\n<div class=\"w3-dropdown-content w3-white w3-card-4 w3-small\">\n<a href=\"/torrents.php\"><i class=\"fa fa-binoculars\"></i> Browse Torrents</a>\n<a href=\"/request.php\"><i class=\"fa fa-ambulance\"></i> Request Torrent</a>\n<a href=\"/torrents-today.php\"><i class=\"fa fa-flash\"></i> Today's Torrents</a>\n</div>\n</li>\n<li class=\"w3-hide-small\"><a href=\"/torrents-upload.php\" class=\"w3-padding-large w3-hover-white\" title=\"Upload Torrent\"><i class=\"fa fa-upload\"></i> Upload Torrent</a></li>\n<li class=\"w3-hide-small\"><a href=\"/torrents-search.php\" class=\"w3-padding-large w3-hover-white\" title=\"Search Torrent\"><i class=\"fa fa-search\"></i> Search</a></li>\n</ul>\n</div>\n</nav>\n \n<script>\nfunction w3_open() {\n    document.getElementById(\"mySidenav\").style.display = \"block\";\n}\nfunction w3_close() {\n    document.getElementById(\"mySidenav\").style.display = \"none\";\n}\n</script>\n<div class='myTable'style=\"margin-top:70px;\">\n \n\n\n            \n\n<script>\n// Accordion\nfunction myFunction(id) {\n    var x = document.getElementById(id);\n    if (x.className.indexOf(\"w3-show\") == -1) {\n        x.className += \" w3-show\";\n        x.previousElementSibling.className += \" w3-theme-d1\";\n    } else {\n        x.className = x.className.replace(\"w3-show\", \"\");\n        x.previousElementSibling.className =\n        x.previousElementSibling.className.replace(\" w3-theme-d1\", \"\");\n    }\n}\n\n// Used to toggle the menu on smaller screens when clicking on the menu button\nfunction openNav() {\n    var x = document.getElementById(\"navDemo\");\n    if (x.className.indexOf(\"w3-show\") == -1) {\n        x.className += \" w3-show\";\n    } else {\n        x.className = x.className.replace(\" w3-show\", \"\");\n    }\n}\n</script>\n  <div id='main'>\n <center>    <table cellspacing=\"8\" cellpadding=\"10\" width=\"100%\" border=\"0\">\n     <tr>\n<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script> \n  <td valign=\"top\"><div class='myFrame'>\n        <div class='myFrame-caption'><h3 class=\"w3-allerta w3-theme-l1\"><center>Browse Torrents</center></h3><a style='float:right; clear:right;' href='#' class='showHide' id='$blockId'></a></div>\n        <div class='myFrame-content'>\n    \n\t\t\n\n    <center><b>Categories:</b>  - <a href='torrents.php'>Show all of</a> - <a href='torrents.php?parent_cat=Anime'>Anime</a> - <a href='torrents.php?parent_cat=Apps'>Apps</a> - <a href='torrents.php?parent_cat=Books'>Books</a> - <a href='torrents.php?parent_cat=Comics'>Comics</a> - <a href='torrents.php?parent_cat=Documentaries'>Documentaries</a> - <a href='torrents.php?parent_cat=Games'>Games</a> - <a href='torrents.php?parent_cat=Movies'>Movies</a> - <a href='torrents.php?parent_cat=Music'>Music</a> - <a href='torrents.php?parent_cat=Other'>Other</a> - <a href='torrents.php?parent_cat=TV'>TV</a> - <a href='torrents.php?parent_cat=TV%2FHD'>TV/HD</a> - <a href='torrents.php?parent_cat=Unity+Asset'>Unity Asset</a> - <a href='torrents.php?parent_cat=XXX'>XXX</a><br /><br />\n\n</center><br /><br /><div align='right'><form id='sort' action=''>Sort By: <select name='sort' onchange='window.location=\"torrents.php?page=1&amp;sort=\"+this.options[this.selectedIndex].value+\"&amp;order=\"+document.forms[\"sort\"].order.options[document.forms[\"sort\"].order.selectedIndex].value'><option value='id' selected='selected'>Added</option><option value='name'>Name</option><option value='comments'>Comments</option><option value='size'>Size</option><option value='times_completed'>Completed</option><option value='seeders'>Seeders</option><option value='leechers'>Leechers</option></select>&nbsp;<select name='order' onchange='window.location=\"torrents.php?page=1&amp;order=\"+this.options[this.selectedIndex].value+\"&amp;sort=\"+document.forms[\"sort\"].sort.options[document.forms[\"sort\"].sort.selectedIndex].value'><option selected='selected' value='asc'>Ascend</option><option value='desc' selected='selected'>Descend</option></select></form></div><table align=\"center\" class=\"ttable_headinner\" width=\"100%\"><thead><tr class=\"ttable_head\"><th width='750' height='5' class='w3-jose' anligne align = 'center'>Torrents Name</th><th width='35' height='1'><i class='fa fa-download w3-text-blue'></i></th><th width='35' height='1'><i class='fa fa-magnet w3-text-red fa-rotate-180' ></i></th><th width='35'  (truncated)
[info] Application magnetissimo exited: shutdown

**Comment by nxtreaming** [comment]
It seems that the "lib/crawler/worldwidetorrents.ex" missing some matching clauses.

**Comment by sergiotapia** [comment]
Thanks for the report, I have a great PR about to land into master that tidies up the crawlers a ton and removes all of these ugly errors. Courtesy @tchoutri  😄

**Comment by tchoutri** [comment]
wooo indeed that looks a bit nasty.
I'll get to work once I'm out of the train :)

**Comment by nxtreaming** [comment]
@sergiotapia  any news for code merge?

**Comment by sergiotapia** [comment]
@nxtreaming In the pipeline. Lots of fixes and a few more parsers. #72

**Comment by nxtreaming** [comment]
fine, I will test
