### ISSUE TITLE
Debian instructions

### ISSUE THREAD

**Issue by bakman2** [sergiotapia/magnetissimo#64]
There are some errors in the Debian instructions:

`sudo apt-get install portgresql redis-server nodejs esl-erlang exlixir git screen`
should be (note postgres/elixir):
`sudo apt-get install postgresql redis-server nodejs esl-erlang elixir git screen`

After creating the database/user

`\l`
`                              List of databases`
`   Name    |  Owner   | Encoding | Collate |  Ctype  |   Access privileges`
`-----------+----------+----------+---------+---------+-----------------------`
 `torrent   | torrent  | UTF8     | C.UTF-8 | C.UTF-8 |`

`\dg`
`                             List of roles`
` Role name |                   Attributes                   | Member of`
`-----------+------------------------------------------------+-----------`
`torrent   | Create DB                                      | {}`

`./config/dev.exs` was edited with the proper info:

`# Configure your database`
`config :magnetissimo, Magnetissimo.Repo,`
`adapter: Ecto.Adapters.Postgres,`
`database: "torrent",`
`username: "torrent",`
`password: "mypass",`
`hostname: "localhost",`
`pool_size: 10`

Executing: ```mix ecto.create```

`** (Mix) The database for Magnetissimo.Repo couldn't be created: FATAL 28000` `(invalid_authorization_specification): role "torrent" does not exist`

I have no idea how to fix this error, the role/user/db exists
Postgres is active and running on port 5433

**Comment by tchoutri** [comment]
@bakman2 Hi! Is it still happening to you?
