### ISSUE TITLE
Link to actual torrent page

### ISSUE THREAD

**Issue by OptimusCrime** [sergiotapia/magnetissimo#65]
I really like this app, but I'd like to have the link to the actual torrent page somewhere. I miss information like torrent contents (files) and description about framerate, resolutions etc. Unless we can scrape these, a simple link to the individual torrent page could be useful.

**Comment by yaroto98** [comment]
I was actually thinking about this the other day. To expand on the idea I think it would awesome if when you click on the torrent (since many of the torrents are copied across sites), there is a drop down accordion that let's you select which torrent site link to choose.

**Comment by sergiotapia** [comment]
I think this is a good idea. We won't be scraping all that additional info but as a good compromise I'll link the torrent back to it's source for users that want that info. Stay tuned!

**Comment by skwerlman** [comment]
This will be difficult now that we're moving most of the scrapers to use RSS

**Comment by tchoutri** [comment]
@skwerlman Actually not that difficult since most RSS feeds include a link to the torrent's page =)
