### ISSUE TITLE
[Request] Support for zooqle (https://zooqle.com/)

### ISSUE THREAD

**Issue by srob650** [sergiotapia/magnetissimo#69]
Title says it all.

**Comment by sergiotapia** [comment]
Hey @srob650 - thanks for the suggestion, I added a nice parser for Zooqle. :)

**Comment by sergiotapia** [comment]
https://github.com/sergiotapia/magnetissimo/pull/72/commits/6c9981be413b03ef6b8d87672cea12de0b656237#diff-50bc770530950e78fa46d95c3e14fa7bR1

Once the PR lands, Magnetissimo will support it.

**Comment by srob650** [comment]
Awesome, thanks! 👍
