### ISSUE TITLE
Typo in debian install

### ISSUE THREAD

**Issue by Mautobu** [sergiotapia/magnetissimo#70]
https://github.com/sergiotapia/magnetissimo/wiki/Usage:-Debian-7

sudo apt-get install portgresql redis-server nodejs esl-erlang exlixir git screen

should be 

sudo apt-get install **postgresql** redis-server nodejs esl-erlang **elixir** git screen

**Comment by sergiotapia** [comment]
Thanks for letting me know! I fixed the typo in the wiki.
