### ISSUE TITLE
sql duplicate key value violates unique constraint "torrents_magnet_index"

### ISSUE THREAD

**Issue by comotion** [sergiotapia/magnetissimo#71]
my postgresql main log gets filled by these errors:

`2017-03-17 02:18:57.782 CET [14146] magnetissimo@magnetissimo_dev ERROR:  duplicate key value violates unique constraint "torrents_magnet_index"`

`2017-03-17 02:18:57.782 CET [14146] magnetissimo@magnetissimo_dev DETAIL:  Key (magnet)=(magnet:?xt=urn:btih:E28C828FFEA0C344DDBCDEDFF2F838D14BFFD545&dn=Lethal+Weapon+S01E18+720p+HDTV+X264-DIMENSION%5Brarbg%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Feddie4.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2017-03-17 02:24:16.048 
`

We're talking gigabytes per day.

**Comment by tchoutri** [comment]
This kind of error shows up because we're not waiting long enough between two crawls.
I'm currently setting the waiting period to 30 minutes, let's see if that brings any benefit.
