### ISSUE TITLE
torrent web link to app

### ISSUE THREAD

**Issue by rlacey221** [sergiotapia/magnetissimo#78]
support for creating apps linked through torrent  web app to download torrent files as a zip file when you create an app on the heroku site

**Comment by tchoutri** [comment]
@rlacey221  Could expand your thoughts about this? You want us to integrate a torrent client or just link it with "an app" (whatever that means)? We already offer the magnet links and you can configure your browser to open them in your favourite desktop client…

**Comment by sergiotapia** [comment]
We offer simple `magnet:` links that you can just click and it'll be opened in whatever default torrent application you have set up.

Can you clarify what you mean by "web link to app"?
