### ISSUE TITLE
Some LimeTorrents listings seem to have odd leacher counts

### ISSUE THREAD

**Issue by TehNut** [sergiotapia/magnetissimo#8]
Like so

![what](http://i.imgur.com/VRjoM5p.png)

I've seen this multiple times while looking through the listings. Haven't seen it for anything but LimeTorrents.

**Comment by sergiotapia** [comment]
Thanks for the name of the torrent and screenshot. I'll check what's up and write a fix to the LimeTorrents parser. :+1:

**Comment by sergiotapia** [comment]
@TehNut It seems LimeTorrents updates it's seeder and leecher information client-side on page load, it's not part of the original source of the page.

Scraping it would be more work that it's worth at this stage so I've defaulted the values to 0 for both seeders and leechers here: https://github.com/sergiotapia/magnetissimo/blob/master/lib/parsers/limetorrents.ex#L60

**Comment by TehNut** [comment]
Ah, fun. And alright. Better than the insane count it was before hehe
