### ISSUE TITLE
Low-priority deep crawl

### ISSUE THREAD

**Issue by skwerlman** [sergiotapia/magnetissimo#82]
Currently, magnetissimo only crawls the latest n torrents from a site. This means that if the crawler is off for some time, any torrents uploaded in that period are never crawled. Additionally, any torrents uploaded more than a short while before the crawler was first started will never be found. As time goes on, the number of "lost" torrents will only grow.

To fix this, it'd be nice to see a crawler which did a deep crawl on each of the supported sites, potentially at a slower rate than the main crawlers. This way, old torrents and missed torrents would eventually be fetched and stored, making them available to the user.

**Comment by pahakalle** [comment]
If magnetissimo will move to rss the deep crawl will become impossible. (unless someone adds it 👍 )
