### ISSUE TITLE
Crash on fresh Debian 7 install

### ISSUE THREAD

**Issue by Hobbabobba** [sergiotapia/magnetissimo#84]
Following the manual I installed magnetissimo on a fresh Debian 7.
The program keeps crashing. Any idea what i did wrong?
[log.txt](https://github.com/sergiotapia/magnetissimo/files/1220513/log.txt)

**Comment by wow-sweetlie** [comment]
Nothing, from what's written in your logs there is no fallback here 

https://github.com/sergiotapia/magnetissimo/blob/51e92afbc776b8a60d8f9e79fc44d6669724dcf9/lib/crawler/helper.ex#L19-L34

you got 503 error, pattern matching didn't work 3 times, the supervisor gave up.

**Comment by Hobbabobba** [comment]
any idea how to fix it?

**Comment by sergiotapia** [comment]
Hi @Hobbabobba the master branch is pretty bad and crashes frequently. There's a PR in the pipeline that addresses all of these issues and runs without a hitch for weeks and weeks - but I just don't have time to dedicate to the project to make it land.

**Comment by Hobbabobba** [comment]
changed the branch to feature/general-cleanup and now i am getting results!
