### ISSUE TITLE
[ADD] x[BiT] as a provider (have rss and api)

### ISSUE THREAD

**Issue by scriptzteam** [sergiotapia/magnetissimo#86]
**https://xbit.pw/readme**

```Base-page search:
https://xbit.pw/?search=ubuntu

Base-RSS:
https://xbit.pw/rss

Base-RSS search:
https://xbit.pw/rss?search=ubuntu

Base-RSS search with limits number of output:
https://xbit.pw/rss?search=ubuntu&limit=5

Basic magnet view:
https://xbit.pw/?id=1

Basic magnet files view:
https://xbit.pw/?files=1

Recently discovered files:
https://xbit.pw/files

Stats page:
https://xbit.pw/stats

---------------------------------------------------------------

Json-API with search and limit output (limit can be max. 100):
https://xbit.pw/api?search=ubuntu&limit=3

Json-API latest 1000:
https://xbit.pw/api

---------------------------------------------------------------

:)

```

**Comment by skwerlman** [comment]
There are unfortunately a couple issues with the site that'll make it hard to get right:

1. No trackers are included in any of the magnet links.
2. There's an empty entry at the end of the `dht_results` tale in API responses.
3. The site's DHT scraper doesn't handle some encodings correctly, resulting in mojibake names. (like this: `[tvN] ì‚¼ì‹œì„¸ë¼ ë°”ë‹¤ëª©ìž¥íŽ¸.E05.170901.720p-NEXT.mp4`)

That said, I'm gonna try and get this site implemented.

**Comment by scriptzteam** [comment]
I dont see the characters like you see them :)

Check https://xbit.pw/?id=106196
Output is `[tvN] 삼시세끼 바다목장편.E05.170901.720p-NEXT.mp4`

All you need to do is URLDECODE the name part :)

`%5BtvN%5D+%EC%82%BC%EC%8B%9C%EC%84%B8%EB%81%BC+%EB%B0%94%EB%8B%A4%EB%AA%A9%EC%9E%A5%ED%8E%B8` --> `https://urldecode.org/?text=%255BtvN%255D%2B%25EC%2582%25BC%25EC%258B%259C%25EC%2584%25B8%25EB%2581%25BC%2B%25EB%25B0%2594%25EB%258B%25A4%25EB%25AA%25A9%25EC%259E%25A5%25ED%258E%25B8&mode=decode`

:)

**Comment by skwerlman** [comment]
I saw the issue with the names appear in the JSON API, so maybe the bug is in how that is generated.

The ID was a copy-paste error, my bad.

**Comment by tchoutri** [comment]
@skwerlman Can we consider starting working on the xBit crawler soon? Or is it bound to be a massive headache? (which doesn't bother me, but it will just lower its priority ;)

**Comment by skwerlman** [comment]
It doesn't look too hard, although the RSS feed is malformed, and neither the feed nor the JSON api contain seeder/leecher counts.

I can either set those to 0, or give up the RSS/API speed improvement and scrape each torrent's detail page. Which is preferable?

**Comment by tchoutri** [comment]
Ideally we should send them an email and kindly ask them to add the relevant details to their API…
I don't like that but let's not make waves yet and use the API, with its flaws :/

**Comment by skwerlman** [comment]
investigating further, it doesn't look like detail pages have seed/leecher counts either, so i guess we'll have to default to 0 either way.

**Comment by tchoutri** [comment]
@skwerlman yeah and I don't feel like crawling the DHT for the infohashes :p Do you think you can spend some time doing this crawler? You can base its architecture on the EZTV crawler :)

**Comment by skwerlman** [comment]
haha that's exactly what i'm doing right now

**Comment by tchoutri** [comment]
Fantastique :)
