### ISSUE TITLE
Immediately shuts down after first run.

### ISSUE THREAD

**Issue by dessalines** [sergiotapia/magnetissimo#87]
Is this still being maintained? On first run I got the message:

```
link: "https://www.limetorrents.cc/browse-torrents/Movies/date/6/"]}
[info] Application magnetissimo exited: shutdown
```

**Comment by pahakalle** [comment]
What OS are you running this on?

**Comment by dessalines** [comment]
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

I got it working, had to read through comments and find that feature branch you're working on, and run migrate again. I highly suggest merging that into master, everyone else is going to run into that problem.

**Comment by dessalines** [comment]
Also it seems to be only fetching from eztv right now, and even though all demonoids are failing it just keeps hitting each one of them.

**Comment by pahakalle** [comment]
Sadly the maintainer is busy with personal stuff and hence hasn't got time to work on this project.

**Comment by dessalines** [comment]
Damn, might have to make my own then.

**Comment by pahakalle** [comment]
After #72 gets merged it should probably fix that issue

**Comment by alexanderadam** [comment]
[PR is now merged](https://github.com/sergiotapia/magnetissimo/pull/72#issuecomment-353640362). Did it fix the issue?

**Comment by tchoutri** [comment]
@dessalines Hi! I'm closing the issue for now, please feel free to complain if the next release crashes on start. :)
