### ISSUE TITLE
Transferring all or as many as possible of the crawlers to use rss.

### ISSUE THREAD

**Issue by pahakalle** [sergiotapia/magnetissimo#89]
Here's a list of sites that currently have a crawler made for them.
---
~~All feeds are the "all feeds", that contain all the torrents~~
**Changed** links to main RSS page (not all had one).

- [ ] [Demonoid](https://www.demonoid.pw)
  - https://www.demonoid.pw/rss.php
- [x] [eztv](https://eztv.ag/)
  - https://eztv.ag/ezrss.xml
- [X] [1337x](https://1337x.to)
  - No RSS feed
- [X] [monova](https://monova.org)
  - No RSS feed
- [ ] [thepiratebay](https://thepiratebay.org/)
  - https://thepiratebay.org/rss/
- [ ] [torrentdownloads](http://www.torrentdownloads.me/)
  - http://www.torrentdownloads.me/rss.xml?type=today
- [ ] [zooqle](https://zooqle.com)
  - OpenSearch + API
- [ ] [rarbg](https://rarbg.to)
  - API
- [x] [nyaa](https://nyaa.si/)
  - https://nyaa.si/?page=rss
- [x] [nyaa.pantsu](https://nyaa.pantsu.cat)
  - https://nyaa.pantsu.cat/feed

**Comment by pahakalle** [comment]
Also once someone merges #77, there will be nyaa.si (pull request is using nyaa.si's rss)

**Comment by tchoutri** [comment]
Awesome, thanks :)

**Comment by sergiotapia** [comment]
Thanks @pahakalle

**Comment by pahakalle** [comment]
If someone has more time in their hands than me, feel free to do these 👍

**Comment by tchoutri** [comment]
I'm opening a PR for EZTV :)

**Comment by tchoutri** [comment]
Demonoid's website is awful, I'm currently doing nasty stuff generating magnet links from the `.torrent` files. Its RSS and API are just useless :/

**Comment by pahakalle** [comment]
Should [thepiratebay.org](https://thepiratebay.org) be move to use one of the proxys like [proxyship.click](https://proxyship.click) (most popular/fastest if i remember correctly), for more stability?

**Comment by tchoutri** [comment]
Well ultimately we may to do that :/ Or just have a bunch of proxies/mirrors in the TPB crawler and iterate over them if there's an error

**Comment by skwerlman** [comment]
@pahakalle it looks like the 500 errors on tpb were transitive; i'm not seeing any errors right now.

**Comment by tchoutri** [comment]
@skwerlman okay great, then we should pay extra attention to those and make sure they don't crash the application :)

**Comment by sergiotapia** [comment]
@pahakalle Great idea, now all the crawlers on `master` use the RSS endpoints and run periodically every 5 seconds. 🔥
